            <ul class="tagcloud">
                    <li style='font-size:medium'><a href='/artist/Brad+Sucks' title='This artist was played 815 times' rel='tag'>Brad Sucks</a></li>
                    <li style='font-size:x-large'><a href='/artist/Ehma' title='This artist was played 1483 times' rel='tag'>Ehma</a></li>
                    <li style='font-size:large'><a href='/artist/Josh+Woodward' title='This artist was played 1278 times' rel='tag'>Josh Woodward</a></li>
                    <li style='font-size:xx-large'><a href='/artist/Professor+Kliq' title='This artist was played 1858 times' rel='tag'>Professor Kliq</a></li>
                    <li style='font-size:small'><a href='/artist/Silence' title='This artist was played 452 times' rel='tag'>Silence</a></li>
                    <li style='font-size:xx-small'><a href='/artist/Torley+on+Piano' title='This artist was played 332 times' rel='tag'>Torley on Piano</a></li>
                    <li style='font-size:xx-large'><a href='/artist/Tryad' title='This artist was played 1620 times' rel='tag'>Tryad</a></li>
                    <li style='font-size:small'><a href='/artist/Windpearl' title='This artist was played 397 times' rel='tag'>Windpearl</a></li>
                    <li style='font-size:large'><a href='/artist/adragante' title='This artist was played 852 times' rel='tag'>adragante</a></li>
                    <li style='font-size:x-small'><a href='/artist/paniq' title='This artist was played 368 times' rel='tag'>paniq</a></li>
        </ul>